//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UNLTDWingsApp
{
    public partial class AccountManagement
  {
      protected global::System.Web.UI.WebControls.LinkButton btnBack;
   protected global::System.Web.UI.WebControls.Button btnShowAdd;
        protected global::System.Web.UI.WebControls.Label lblMessage;
    protected global::System.Web.UI.WebControls.Panel pnlForm;
        protected global::System.Web.UI.WebControls.Label lblFormTitle;
        protected global::System.Web.UI.WebControls.HiddenField hfUserID;
  protected global::System.Web.UI.WebControls.TextBox txtName;
  protected global::System.Web.UI.WebControls.TextBox txtUsername;
        protected global::System.Web.UI.WebControls.DropDownList ddlRole;
     protected global::System.Web.UI.WebControls.Label lblPasswordNote;
  protected global::System.Web.UI.WebControls.TextBox txtPassword;
        protected global::System.Web.UI.WebControls.Button btnSave;
        protected global::System.Web.UI.WebControls.Button btnCancelForm;
        protected global::System.Web.UI.WebControls.Label lblUserCount;
      protected global::System.Web.UI.WebControls.Repeater rptUsers;
        protected global::System.Web.UI.WebControls.Panel pnlNoUsers;
    }
}
