//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UNLTDWingsApp
{
    public partial class Dashboard
    {
        protected global::System.Web.UI.WebControls.LinkButton btnLogout;
        protected global::System.Web.UI.WebControls.Label lblUserName;
        protected global::System.Web.UI.WebControls.Label lblRole;
        protected global::System.Web.UI.WebControls.LinkButton btnPendingAlert;
        protected global::System.Web.UI.WebControls.Panel pnlPendingAlert;
        protected global::System.Web.UI.WebControls.Label lblPendingCount;
        protected global::System.Web.UI.WebControls.Label lblTodaySales;
        protected global::System.Web.UI.WebControls.Label lblTodayOrders;
        protected global::System.Web.UI.WebControls.Label lblTodayRefills;
        protected global::System.Web.UI.WebControls.LinkButton btnWalkIn;
        protected global::System.Web.UI.WebControls.LinkButton btnTakeOut;
        protected global::System.Web.UI.WebControls.LinkButton btnDelivery;
        protected global::System.Web.UI.WebControls.LinkButton btnRefill;
        protected global::System.Web.UI.WebControls.LinkButton btnTodaysOrders;
        protected global::System.Web.UI.WebControls.LinkButton btnPendingOrders;
        protected global::System.Web.UI.WebControls.Panel pnlAdminActions;
        protected global::System.Web.UI.WebControls.LinkButton btnMenu;
        protected global::System.Web.UI.WebControls.LinkButton btnInventory;
        protected global::System.Web.UI.WebControls.LinkButton btnReports;
        protected global::System.Web.UI.WebControls.LinkButton btnAccounts;
        protected global::System.Web.UI.WebControls.LinkButton btnQRCodes;
        protected global::System.Web.UI.WebControls.Panel pnlLowStock;
        protected global::System.Web.UI.WebControls.Repeater rptLowStock;
    }
}
