//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UNLTDWingsApp
{
    public partial class GuestCart
    {
        protected global::System.Web.UI.WebControls.Label lblAccountType;
        protected global::System.Web.UI.WebControls.Label lblGuestName;
        protected global::System.Web.UI.WebControls.LinkButton btnLogout;
        protected global::System.Web.UI.WebControls.Panel pnlSuccess;
        protected global::System.Web.UI.WebControls.Panel pnlCart;
        protected global::System.Web.UI.WebControls.Repeater rptCartItems;
        protected global::System.Web.UI.WebControls.Label lblOrderType;
        protected global::System.Web.UI.WebControls.Panel pnlGuestFields;
        protected global::System.Web.UI.WebControls.TextBox txtGuestName;
        protected global::System.Web.UI.WebControls.Panel pnlContactField;
        protected global::System.Web.UI.WebControls.TextBox txtContact;
        protected global::System.Web.UI.WebControls.Panel pnlAddress;
        protected global::System.Web.UI.WebControls.TextBox txtAddress;
        protected global::System.Web.UI.WebControls.Panel pnlTableInfo;
        protected global::System.Web.UI.WebControls.Label lblTableNum;
        protected global::System.Web.UI.WebControls.DropDownList ddlPaymentMethod;
        protected global::System.Web.UI.WebControls.Panel pnlGcash;
        protected global::System.Web.UI.WebControls.TextBox txtGcashReference;
        protected global::System.Web.UI.WebControls.Label lblSubtotal;
        protected global::System.Web.UI.WebControls.Label lblItemCount;
        protected global::System.Web.UI.WebControls.Label lblTotal;
        protected global::System.Web.UI.WebControls.Button btnSubmitOrder;
        protected global::System.Web.UI.WebControls.Label lblMessage;
        protected global::System.Web.UI.WebControls.Panel pnlEmptyCart;
    }
}
