//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UNLTDWingsApp
{
 public partial class GuestOrders
 {
 protected global::System.Web.UI.WebControls.LinkButton btnBack;
 protected global::System.Web.UI.WebControls.Repeater rptOrders;
 protected global::System.Web.UI.WebControls.Panel pnlEmpty;
 }
}
