//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UNLTDWingsApp
{
    public partial class GuestWelcome
    {
        protected global::System.Web.UI.WebControls.Label lblError;
        protected global::System.Web.UI.WebControls.LinkButton btnTakeout;
        protected global::System.Web.UI.WebControls.LinkButton btnDelivery;
    }
}
