//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UNLTDWingsApp
{
    public partial class GuestMenu
 {
        protected global::System.Web.UI.ScriptManager ScriptManager1;
        protected global::System.Web.UI.WebControls.Label lblAccountType;
        protected global::System.Web.UI.WebControls.Label lblGuestName;
        protected global::System.Web.UI.WebControls.LinkButton btnLogout;
        protected global::System.Web.UI.WebControls.LinkButton btnAll;
     protected global::System.Web.UI.WebControls.LinkButton btnUnlimited;
        protected global::System.Web.UI.WebControls.LinkButton btnWings;
        protected global::System.Web.UI.WebControls.LinkButton btnRiceMeals;
   protected global::System.Web.UI.WebControls.LinkButton btnPasta;
protected global::System.Web.UI.WebControls.LinkButton btnCombos;
protected global::System.Web.UI.WebControls.LinkButton btnFries;
        protected global::System.Web.UI.WebControls.LinkButton btnDrinks;
        protected global::System.Web.UI.WebControls.LinkButton btnAddons;
        protected global::System.Web.UI.WebControls.Repeater rptTopFavourites;
        protected global::System.Web.UI.UpdatePanel UpdatePanel1;
        protected global::System.Web.UI.WebControls.Repeater rptMenuItems;
        protected global::System.Web.UI.WebControls.Panel pnlEmpty;
        protected global::System.Web.UI.WebControls.Label lblCartCount;
        protected global::System.Web.UI.WebControls.HiddenField hfShowToast;
    }
}
