//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UNLTDWingsApp
{
    public partial class InventoryManagement
    {
        protected global::System.Web.UI.WebControls.LinkButton btnBack;
        protected global::System.Web.UI.WebControls.Button btnShowAdd;
   protected global::System.Web.UI.WebControls.Label lblMessage;
        protected global::System.Web.UI.WebControls.Label lblTotalItems;
        protected global::System.Web.UI.WebControls.Label lblLowStock;
        protected global::System.Web.UI.WebControls.Label lblOutOfStock;
        protected global::System.Web.UI.WebControls.Panel pnlRestock;
   protected global::System.Web.UI.WebControls.Label lblRestockItem;
  protected global::System.Web.UI.WebControls.HiddenField hfRestockID;
        protected global::System.Web.UI.WebControls.TextBox txtRestockQty;
     protected global::System.Web.UI.WebControls.Button btnConfirmRestock;
    protected global::System.Web.UI.WebControls.Button btnCancelRestock;
        protected global::System.Web.UI.WebControls.Panel pnlForm;
        protected global::System.Web.UI.WebControls.Label lblFormTitle;
        protected global::System.Web.UI.WebControls.HiddenField hfItemID;
 protected global::System.Web.UI.WebControls.TextBox txtIngredientName;
     protected global::System.Web.UI.WebControls.TextBox txtStockLevel;
      protected global::System.Web.UI.WebControls.DropDownList ddlUnit;
        protected global::System.Web.UI.WebControls.TextBox txtReorderLevel;
  protected global::System.Web.UI.WebControls.Button btnSave;
 protected global::System.Web.UI.WebControls.Button btnCancelForm;
        protected global::System.Web.UI.WebControls.Repeater rptInventory;
      protected global::System.Web.UI.WebControls.Panel pnlNoItems;
    }
}
