//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UNLTDWingsApp
{
    public partial class MenuManagement
    {
  protected global::System.Web.UI.WebControls.LinkButton btnBack;
        protected global::System.Web.UI.WebControls.Button btnShowAdd;
  protected global::System.Web.UI.WebControls.Label lblMessage;
        protected global::System.Web.UI.WebControls.Panel pnlForm;
      protected global::System.Web.UI.WebControls.Label lblFormTitle;
     protected global::System.Web.UI.WebControls.HiddenField hfItemID;
  protected global::System.Web.UI.WebControls.TextBox txtItemName;
        protected global::System.Web.UI.WebControls.TextBox txtDescription;
        protected global::System.Web.UI.WebControls.DropDownList ddlCategory;
  protected global::System.Web.UI.WebControls.TextBox txtPrice;
    protected global::System.Web.UI.WebControls.CheckBox chkAvailable;
        protected global::System.Web.UI.WebControls.Button btnSave;
        protected global::System.Web.UI.WebControls.Button btnCancelForm;
        protected global::System.Web.UI.WebControls.Label lblItemCount;
    protected global::System.Web.UI.WebControls.LinkButton btnFilterAll;
    protected global::System.Web.UI.WebControls.LinkButton btnFilterUnlimited;
      protected global::System.Web.UI.WebControls.LinkButton btnFilterWings;
    protected global::System.Web.UI.WebControls.LinkButton btnFilterRice;
        protected global::System.Web.UI.WebControls.LinkButton btnFilterPasta;
     protected global::System.Web.UI.WebControls.LinkButton btnFilterCombos;
        protected global::System.Web.UI.WebControls.LinkButton btnFilterFries;
      protected global::System.Web.UI.WebControls.LinkButton btnFilterDrinks;
        protected global::System.Web.UI.WebControls.LinkButton btnFilterAddons;
        protected global::System.Web.UI.WebControls.Repeater rptMenuItems;
        protected global::System.Web.UI.WebControls.Panel pnlNoItems;
    }
}
