//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UNLTDWingsApp
{
 public partial class OrderDetails
 {
 protected global::System.Web.UI.WebControls.Label lblOrderId;
 protected global::System.Web.UI.WebControls.Panel pnlNotFound;
 protected global::System.Web.UI.WebControls.Panel pnlDetails;
 protected global::System.Web.UI.WebControls.Label lblCustomer;
 protected global::System.Web.UI.WebControls.Label lblType;
 protected global::System.Web.UI.WebControls.Label lblTable;
 protected global::System.Web.UI.WebControls.Label lblAddress;
 protected global::System.Web.UI.WebControls.Label lblContact;
 protected global::System.Web.UI.WebControls.Label lblPayment;
 protected global::System.Web.UI.WebControls.Label lblRef;
 protected global::System.Web.UI.WebControls.Label lblStatus;
 protected global::System.Web.UI.WebControls.Label lblDate;
 protected global::System.Web.UI.WebControls.Panel pnlItems;
 protected global::System.Web.UI.WebControls.GridView gvItems;
 protected global::System.Web.UI.WebControls.Label lblTotal;
 }
}
