//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UNLTDWingsApp
{
    public partial class QRCodeManagement
    {
  protected global::System.Web.UI.WebControls.LinkButton btnBack;
 protected global::System.Web.UI.WebControls.Button btnShowAdd;
 protected global::System.Web.UI.WebControls.Label lblMessage;
        protected global::System.Web.UI.WebControls.Panel pnlForm;
  protected global::System.Web.UI.WebControls.Label lblFormTitle;
        protected global::System.Web.UI.WebControls.HiddenField hfQRCodeID;
        protected global::System.Web.UI.WebControls.TextBox txtTableNumber;
        protected global::System.Web.UI.WebControls.TextBox txtTableDescription;
        protected global::System.Web.UI.WebControls.TextBox txtCustomUrl;
        protected global::System.Web.UI.WebControls.CheckBox chkActive;
        protected global::System.Web.UI.WebControls.Button btnSave;
        protected global::System.Web.UI.WebControls.Button btnCancelForm;
        protected global::System.Web.UI.WebControls.Label lblQRCount;
   protected global::System.Web.UI.WebControls.Repeater rptQRCodes;
   protected global::System.Web.UI.WebControls.Panel pnlNoQRCodes;
  }
}
