//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UNLTDWingsApp
{
    public partial class Reports
    {
  protected global::System.Web.UI.WebControls.LinkButton btnBack;
   protected global::System.Web.UI.WebControls.TextBox txtStartDate;
       protected global::System.Web.UI.WebControls.TextBox txtEndDate;
  protected global::System.Web.UI.WebControls.Button btnGenerate;
    protected global::System.Web.UI.WebControls.Label lblTodaySales;
 protected global::System.Web.UI.WebControls.Label lblTodayOrders;
        protected global::System.Web.UI.WebControls.Label lblWeekSales;
        protected global::System.Web.UI.WebControls.Label lblMonthSales;
        protected global::System.Web.UI.WebControls.Panel pnlReport;
   protected global::System.Web.UI.WebControls.Label lblTotalSales;
        protected global::System.Web.UI.WebControls.Label lblTotalOrders;
        protected global::System.Web.UI.WebControls.Label lblAvgOrder;
        protected global::System.Web.UI.WebControls.Repeater rptTopItems;
    protected global::System.Web.UI.WebControls.Repeater rptOrders;
    }
}
