//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace UNLTDWingsApp {
    
    
    public partial class TodaysOrders {

        /// <summary>
   /// form1 control.
        /// </summary>
     protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        /// <summary>
        /// lblOrderCount control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblOrderCount;

        /// <summary>
     /// lblActiveCount control.
        /// </summary>
     protected global::System.Web.UI.WebControls.Label lblActiveCount;
 
        /// <summary>
    /// lblCompletedCount control.
        /// </summary>
    protected global::System.Web.UI.WebControls.Label lblCompletedCount;
        
        /// <summary>
/// lblTotalRevenue control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblTotalRevenue;

/// <summary>
        /// lblLowStockCount control.
 /// </summary>
        protected global::System.Web.UI.WebControls.Label lblLowStockCount;
        
        /// <summary>
     /// btnFilterAll control.
        /// </summary>
   protected global::System.Web.UI.WebControls.LinkButton btnFilterAll;
        
  /// <summary>
     /// btnFilterDineIn control.
        /// </summary>
        protected global::System.Web.UI.WebControls.LinkButton btnFilterDineIn;
        
        /// <summary>
        /// btnFilterDelivery control.
     /// </summary>
    protected global::System.Web.UI.WebControls.LinkButton btnFilterDelivery;
  
        /// <summary>
        /// btnFilterTakeout control.
        /// </summary>
        protected global::System.Web.UI.WebControls.LinkButton btnFilterTakeout;
        
/// <summary>
        /// txtSearch control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtSearch;

        /// <summary>
     /// btnSearch control.
  /// </summary>
        protected global::System.Web.UI.WebControls.Button btnSearch;
        
    /// <summary>
        /// btnClearSearch control.
        /// </summary>
  protected global::System.Web.UI.WebControls.Button btnClearSearch;
  
        /// <summary>
     /// pnlOrders control.
 /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlOrders;
        
        /// <summary>
        /// rptOrders control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptOrders;
        
        /// <summary>
        /// pnlEmpty control.
      /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlEmpty;
        
        /// <summary>
        /// btnBack control.
        /// </summary>
      protected global::System.Web.UI.WebControls.LinkButton btnBack;

        /// <summary>
    /// btnRefreshHidden control.
   /// </summary>
        protected global::System.Web.UI.WebControls.Button btnRefreshHidden;
    }
}
